services:

  caddy:
    image: caddy:2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./staticfiles:/app/staticfiles
    network_mode: "host"  # This allows Caddy to access all networks

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    driver: bridge 