# Generated by Django 5.1.5 on 2025-01-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subnet', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255)),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('environment_vars', models.TextField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='xwangnet.dockernetwork')),
            ],
        ),
    ]
