# Generated by Django 5.1.5 on 2025-01-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0002_devicetemplate_networkconfiguration_deviceinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='devicetemplate',
            name='build_instructions',
            field=models.TextField(blank=True, help_text='Instructions for building this device image'),
        ),
        migrations.AddField(
            model_name='devicetemplate',
            name='docker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicetemplate',
            name='docker_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='devicetemplate',
            name='environment',
            field=models.JSONField(default=dict, help_text='Default environment variables'),
        ),
        migrations.AddField(
            model_name='devicetemplate',
            name='ports',
            field=models.JSONField(default=dict, help_text='Default ports to expose'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetemplate',
            unique_together={('name', 'version')},
        ),
    ]
