# Generated by Django 5.1.5 on 2025-01-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0003_alter_devicetemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network_status', models.CharField(default='down', max_length=50)),
                ('docker_network_id', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwangnet.networkconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='DeployedContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='stopped', max_length=50)),
                ('hostname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwangnet.devicetemplate')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='xwangnet.deployment')),
            ],
        ),
    ]
