# Generated by Django 5.1.5 on 2025-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0004_deployment_deployedcontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconfiguration',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
