# Generated by Django 5.1.5 on 2025-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0005_alter_networkconfiguration_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='snort_container_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='snort_status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='docker_network_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='network_status',
            field=models.CharField(default='down', max_length=10),
        ),
    ]
