# Generated by Django 5.1.5 on 2025-02-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0006_deployment_snort_container_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='snort_container_id',
            new_name='suricata_container_id',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='snort_status',
            new_name='suricata_status',
        ),
    ]
