# Generated by Django 5.1.5 on 2025-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0007_rename_snort_container_id_deployment_suricata_container_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedcontainer',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
