# Generated by Django 5.1.5 on 2025-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0008_alter_deployedcontainer_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedcontainer',
            name='internal_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
