# Generated by Django 5.1.5 on 2025-02-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0009_deployedcontainer_internal_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkconfiguration',
            name='network_type',
        ),
        migrations.AddField(
            model_name='networkconfiguration',
            name='isolated',
            field=models.BooleanField(default=False),
        ),
    ]
