# Generated by Django 5.1.5 on 2025-03-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0010_remove_networkconfiguration_network_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercontainer',
            name='network',
        ),
        migrations.DeleteModel(
            name='DeviceInstance',
        ),
        migrations.DeleteModel(
            name='DockerContainer',
        ),
        migrations.DeleteModel(
            name='DockerNetwork',
        ),
    ]
