# Generated by Django 5.1.5 on 2025-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwangnet', '0011_remove_dockercontainer_network_delete_deviceinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='log_file_path',
            field=models.CharField(blank=True, help_text='Path to log file inside container to tail (e.g., /var/log/app.log)', max_length=500, null=True),
        ),
    ]
